### ISSUE TITLE
Feature Request - support Exa

### ISSUE THREAD

**Issue by jonbarksdale** [b0o/zfzf#1]
When trying to use zfzf with exa, I get `exa: Unknown argument -A`

For reference, I'm using https://github.com/zpm-zsh/ls as an ls bridge, so it's likely the two conflict. 

Steps to repro: 
1) install https://github.com/zpm-zsh/ls with zfzf
2) go to a dir, hit Alt+.

Notice there is an error message, and only . & .. are selectable, no matter whats in the directory.

**Comment by b0o** [comment]
Thank you for your report! 

I've pushed some changes that I think should fix this, would you mind testing with the latest version?

**Comment by jonbarksdale** [comment]
Seems to work great! thanks!
